// Generated by tools/export_behavior_model.py. Do not edit by hand.
#pragma once

#include <math.h>

namespace cozmo_ml {

enum class Intent : unsigned char {
    INTENT_IDLE = 0,
    INTENT_ANGRY = 1,
    INTENT_ANNOYED = 2,
    INTENT_SLEEPY = 3,
    INTENT_ATTENTION = 4,
    INTENT_PLAYFUL = 5
};

struct Features {
  float values[7];
};

struct Prediction {
  Intent intent;
  float confidence;
};

constexpr int kClassCount = 6;
constexpr int kFeatureCount = 7;
static const float kBias[kClassCount] = {1.0615088434f, -0.5504573102f, 1.9888624270f, 2.2638058466f, -1.4068493850f, -3.3568704218f};
static const float kWeights[kClassCount][kFeatureCount] = {
    {1.4807520819f, -0.3869533898f, -1.8659774013f, -1.2119508550f, 1.5765294204f, 0.0163502919f, -2.1857719631f},
    {-1.1614562373f, -2.2781053318f, 4.5127683879f, -0.4763957188f, 0.2437915201f, 0.0259288689f, 5.5060289339f},
    {-3.6289221291f, -1.7093270349f, 0.9063697259f, 0.0712161759f, 0.2744542954f, 0.0761740442f, 1.9195950643f},
    {-6.0186517648f, 0.8423206107f, -2.1461750171f, 0.0489247903f, 0.2823211718f, 0.0979945400f, -3.1331032868f},
    {3.7024950624f, 0.4563431070f, -1.0297926306f, 3.0390952433f, -3.9121220456f, -0.0691340566f, -1.5060836389f},
    {5.6257829869f, 3.0757220387f, -0.3771930648f, -1.4708896357f, 1.5350256380f, -0.1473136883f, -0.6006651094f}
};

inline Prediction predict(const Features& features) {
  float logits[kClassCount];
  for (int class_index = 0; class_index < kClassCount; ++class_index) {
    logits[class_index] = kBias[class_index];
    for (int feature_index = 0; feature_index < kFeatureCount; ++feature_index) {
      logits[class_index] += kWeights[class_index][feature_index] * features.values[feature_index];
    }
  }

  float maximum = logits[0];
  for (int class_index = 1; class_index < kClassCount; ++class_index) {
    if (logits[class_index] > maximum) maximum = logits[class_index];
  }

  float total = 0.0f;
  float probabilities[kClassCount];
  for (int class_index = 0; class_index < kClassCount; ++class_index) {
    probabilities[class_index] = expf(logits[class_index] - maximum);
    total += probabilities[class_index];
  }

  int best_index = 0;
  for (int class_index = 1; class_index < kClassCount; ++class_index) {
    if (probabilities[class_index] > probabilities[best_index]) best_index = class_index;
  }
  return {static_cast<Intent>(best_index), probabilities[best_index] / total};
}

}  // namespace cozmo_ml
