#!/usr/bin/env python3
"""Train and export the CozmoMini behavior model for embedded inference."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys
import tempfile

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from ml.behavior_model import CLASS_NAMES, FEATURE_NAMES, generate_dataset, train


EPOCHS = 1800
LEARNING_RATE = 0.25
L2 = 0.001


def format_float(value: float) -> str:
    if abs(value) < 0.00000000005:
        value = 0.0
    return f"{value:.10f}f"


def render_header(model) -> str:
    weights = ",\n".join(
        "    {" + ", ".join(format_float(value) for value in row) + "}"
        for row in model.weights
    )
    bias = ", ".join(format_float(value) for value in model.bias)
    enum_values = ",\n    ".join(
        f"INTENT_{class_name} = {index}" for index, class_name in enumerate(CLASS_NAMES)
    )
    return f'''// Generated by tools/export_behavior_model.py. Do not edit by hand.
#pragma once

#include <math.h>

namespace cozmo_ml {{

enum class Intent : unsigned char {{
    {enum_values}
}};

struct Features {{
  float values[{len(FEATURE_NAMES)}];
}};

struct Prediction {{
  Intent intent;
  float confidence;
}};

constexpr int kClassCount = {len(CLASS_NAMES)};
constexpr int kFeatureCount = {len(FEATURE_NAMES)};
static const float kBias[kClassCount] = {{{bias}}};
static const float kWeights[kClassCount][kFeatureCount] = {{
{weights}
}};

inline Prediction predict(const Features& features) {{
  float logits[kClassCount];
  for (int class_index = 0; class_index < kClassCount; ++class_index) {{
    logits[class_index] = kBias[class_index];
    for (int feature_index = 0; feature_index < kFeatureCount; ++feature_index) {{
      logits[class_index] += kWeights[class_index][feature_index] * features.values[feature_index];
    }}
  }}

  float maximum = logits[0];
  for (int class_index = 1; class_index < kClassCount; ++class_index) {{
    if (logits[class_index] > maximum) maximum = logits[class_index];
  }}

  float total = 0.0f;
  float probabilities[kClassCount];
  for (int class_index = 0; class_index < kClassCount; ++class_index) {{
    probabilities[class_index] = expf(logits[class_index] - maximum);
    total += probabilities[class_index];
  }}

  int best_index = 0;
  for (int class_index = 1; class_index < kClassCount; ++class_index) {{
    if (probabilities[class_index] > probabilities[best_index]) best_index = class_index;
  }}
  return {{static_cast<Intent>(best_index), probabilities[best_index] / total}};
}}

}}  // namespace cozmo_ml
'''


def render_metadata(dataset_size: int) -> str:
    metadata = {
        "model": "multiclass_softmax_regression",
        "features": list(FEATURE_NAMES),
        "classes": list(CLASS_NAMES),
        "dataset_size": dataset_size,
        "examples_per_class": dataset_size // len(CLASS_NAMES),
        "epochs": EPOCHS,
        "learning_rate": LEARNING_RATE,
        "l2": L2,
        "confidence_threshold": 0.78,
        "label_source": "deterministic expert policy",
    }
    return json.dumps(metadata, indent=2, sort_keys=True) + "\n"


def export(output_dir: Path) -> None:
    states, labels = generate_dataset()
    model = train(
        states,
        labels,
        epochs=EPOCHS,
        learning_rate=LEARNING_RATE,
        l2=L2,
    )
    output_dir.mkdir(parents=True, exist_ok=True)
    (output_dir / "behavior_model.h").write_text(render_header(model))
    (output_dir / "behavior_model.json").write_text(render_metadata(len(states)))


def check_committed_artifacts(repo_root: Path) -> None:
    with tempfile.TemporaryDirectory() as temporary_directory:
        generated_dir = Path(temporary_directory)
        export(generated_dir)
        for filename in ("behavior_model.h", "behavior_model.json"):
            committed = repo_root / "ml" / filename
            generated = generated_dir / filename
            if not committed.exists() or committed.read_bytes() != generated.read_bytes():
                raise SystemExit(f"generated artifact differs: {committed}")
    print("behavior model artifacts are reproducible")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output-dir", type=Path, default=Path("ml"))
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    repo_root = REPO_ROOT
    if args.check:
        check_committed_artifacts(repo_root)
    else:
        export(args.output_dir)
        print(f"exported behavior model to {args.output_dir}")


if __name__ == "__main__":
    main()
